### ISSUE TITLE
Review messages

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-jwt#13]
If necessary, review the text what we have in the web pages, response messages as well as System.out with @sishida.

- [x] Comments in code etc should be proper too.  At least, be consistent in style and capitalization and explain why and what clearly.

- [x] For example, https://github.com/OpenLiberty/draft-guide-microprofile-jwt/blob/master/finish/frontendUI/src/main/webapp/error.xhtml can be improved.

- [x] "Current OS" and "JWT Token string" in the system page too.  What is "Current OS"?  Should it be "Your current OS"?  And, "Your JSON Web Token"?

**Comment by JunyiSun** [comment]
<img width="1658" alt="screen shot 2018-03-05 at 5 16 17 pm" src="https://user-images.githubusercontent.com/12009928/37002853-0a7945d4-2099-11e8-85da-97c470675512.png">

**Comment by sishida** [comment]
Suggested change:

A form login authentication failure occurred.
The user name or password might be incorrect, or the user might not exist.
