### ISSUE TITLE
Rename runAPP as runApp

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-jwt#2]
- 'runAPP' should be 'runApp'
- Left over path for sharedKeystore still?  Should be cleanly under resources

**Comment by JunyiSun** [comment]
@jamiecoleman92 I just realized that the `runApp` folder was reverted back to `runAPP`, and `sharedKeystore/` is accidentally committed back in to the finish folder again in your latest commit (it was renamed to `resources/`), please take a close look, and if possible, can you save your local repo changes to somewhere, and reset the master to commit `31937a194cc7ea912b868e7ef36dfc2addebf877` , and then do a git pull from master, then re-apply your changes? Thank you!
