### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-jwt#27]
(1) These are confusing:

_Open the start/backendServices/src/main/java/io/openliberty/guides/system/SystemResource.java file and modify it to match the following code:

In the start/backendServices/src/main/java/io/openliberty/guides/inventory/ directory, open the InventoryResource.java file and add roles-based access control as shown in the following command:

Add the SecureSystemClient class in the start/backendServices/src/main/java/io/openliberty/guides/inventory/client/SecureSystemClient.java file._

And users can run into trouble, which we have seen before.

Since these files are provided to the users and they aren't empty.  An instruction like "A simple way to proceed is to copy all the code below and replace the content of the file" should be added.

(2) Should we remind users where they should run mvn commands?

Under "Building and running the application" as well as for "Testing the application".  Users might be under some other directories and if we don't remind them where to go back to run the mvn commands, they may run into trouble.

(3) The test output should be no_copyable?

**Comment by JunyiSun** [comment]
(1) and (3) are fixed by #28 , (2) should be fixed through guide-commons
