### ISSUE TITLE
Clarification of some concepts in this guide

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/draft-guide-microprofile-jwt#3]
@jamiecoleman92 
1. Please make sure you understand the difference among these terms and use them correctly in the guide. 
`JWT` - JSON Web Token, not java web token, (I have fixed all places which previously said java web token, but pay attention to it later on). It refers to the token itself,  it can contain information about anything which you want to propagate. It does not do authentication.

`MicroProfile JWT`, or `mp-jwt`: It is security specific, it is the mechanism that injects the JSON web token to the services from the HTTP authorization header, acts like a consumer, and `@RolesAllowed({"admin", "user"})` is only used when mp-jwt is enabled. 
Please do not use the word `JWT` alone when it actually refers to `MP-JWT`. For more information, please check: https://www.eclipse.org/community/eclipse_newsletter/2017/september/article2.php

`JWT builder`:  builder for building the JSON Web Token, it is used only in the LoginBean.java file in the frontendUI folder.

Again, JWT does not perform authentication. MP-JWT performs token based authentication and authorization. The front-end authentication part in our app is the doLogin() function in the LoginBean.java file.

2.  I feel that in a lot of places in the guide, we should use "authorization" instead of "authentication"

3. You don't need to talk about import packages. neither the pom.xml files

4. TO-DO: CHANGE ALL 2017 TO 2018 IN THE COPYRIGHT HEADER

**Comment by JunyiSun** [comment]
@evelinec @yeekangc  FYI

**Comment by jamiecoleman92** [comment]
Licence update done! Just going through the rest of the guide :)

**Comment by jamiecoleman92** [comment]
Made my changes, Gkerta is now doing the peer review.

**Comment by gkertaseferi** [comment]
What you'll learn
1.The great benefit from adding JWT security to your microservices allows you to allow certain groups of users access to 
specific functions. --> 
to your microservices is that it allows certain groups of users to access specific functions

2.You will add JWT authentication and authorization to the microservices provided: SystemResource and InventoryResource while
we provide you with a simple front end to handle the authentication. --> 
You will add JWT authentication and authorization to the microservices provided: SystemResource and InventoryResource while 
aa simple front end to handle the authentication is also provided.

Try what you’ll build
1.(which means you are forbidden from accessing the inventory size data in the back end) --> I don't know if it's good to have parenthesis.
If something is in parenthesis it means that it's not so important to explain.

Adding JWT builder and form-based login to the front-End
1.We have provided you with a very simple front-end web application to allow you to log into the application with pre defined users that 
have different roles such as admin and user.
-->
A very simple front-end web application is provided to allow you to log into the application with pre defined users that 
have different roles such as admin and user.

2.An User class has --> A user class

3.This is an user model --> This is a user model

4.Create a http session --> Create an http session


5.I think there is a better way of saying this, like linking them somehow, it seems like a dictionary now:

The getOs() method returns a String of the operating system for the session from the back-end by doing a GET request with the auth header containing the JSON Web Token.

The getInvSize() method returns the size of the inventory list for a given user from the session.

The getJwt() method returns the JSON Web Token for the current session.

The getUserName() method returns the username of the user currently logged in from the session.

The getUserRole() method returns the role of the currently logged in user.


6.When the open Liberty application server has started you can log into the system using the simple front-end that has been provided. Use one of the following
credentials below to log in:
http://localhost:9090/system.jsf --> I think you should say something about the enpoint, I mean you just write the endpoint without linking th
the things.

7.system, the size of your inventory and the JSON Web Token (JWT) that is being used for authorization in the back end. -->
system and the size of your inventory and the JSON Web Token (JWT) that is being used for authorization in the back end.

Testing
1.Each test case tries to first assert that, with a valid authorization header, it can can get a Status.OK code from the response. -->
Each test case tries to first assert that with a valid authorization header it can get a Status.OK code from the response.

**Comment by jamiecoleman92** [comment]
Changes made! Thanks @gkertaseferi
