### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/draft-guide-microprofile-jwt#4]
- [x] missing LICENSE file
- [x] the start directory is empty
=> @Kubik42 had made the first try to prepare the start directory, pls try it out and see everything in place
- [x] convert all indentation from 2 tabs to 4
- [ ] `finish/pom.xml` has duplicate dependencies defined in `depedencies` and under `dependencyManagement`. Most importantly, these are test dependencies but they have scopes set to "compile". Why do you need test libraries at compile time (these only seem to matter for the `resource` project)? I suspect that this is because your tests are defined under the `main` directory, while they should be under the `test` directory and the integration test plugin should then point to that test directory. In any case, unless this inentional, this needs to be fixed, otherwise its just inconsistent with other guides and all in all just bad practice.
- [x] When you breakdown the methods (and especially when there are a lot of methods to breakdown, like in "Creating the system bean") use bullet points instead of new paragraphs for each method. Say something like "Let's break down the methods:" and then list them
- [x] Clean up the extra white space in finish/pom.xml
- [x] Dont need a `.gitignore` under finish/resources. The only `.gitignore` you should have is under the root directory of the guide
- [x] Fix indentation in `finish/frontendUI/pom.xml`
- [x] `finish/frontendUI/src/main/webapp/META-INF/MANIFEST.MF` shouldn't be commited. You should add "MANIFEST.MF" to your `.gitignore`
- [x] Extra space in `finish/frontendUI/src/main/java/io/openliberty/guides/ui/util/ServiceUtils.java` in `getPropertiesHelper()` (extra line before code), `getInventoryHelper()` (extra line before code), and `invOkHelper()` (extra lines after code).
- [x] profiles in `finish/backendServices/pom.xml` are not used for anything
- [x] Inconsistent indentation and extra white space in `finish/backendServices/pom.xml`
- [x] Extra space in `finish/backendServices/src/test/java/it/io/openliberty/guides/jwt/JwtTest.java` in `testJWTGetName()` (extra line before code) and in `testJWTGetCustomClaim()` (extra line before code).
- [x] Extra white space in `finish/backendServices/src/main/liberty/config/server.xml`
- [x] Extra white space in `finish/backendServices/src/main/java/io/openliberty/guides/system/SystemApplication.java` (line 16). Same for `finish/backendServices/src/main/java/io/openliberty/guides/inventory/InventoryApplication.java`
- [x] `finish/backendServices/pom.xml` is missing scope for `javax.annotation-api`
- [x] `finish/frontendUI/pom.xml` is missing scopes for `microprofile-jwt-auth-api` and `com.ibm.websphere.appserver.api.jwt`
- [ ] Decencies in `finish/resources/pom.xml` are either all missing version or don't need scopes because they are already defined in the parent pom
- [x] `finish/pom.xml` is missing scopes for `com.ibm.websphere.appserver.api.jwt` and `microprofile-config-api`

**What you’ll learn**
- [x] "allows certain groups of users access to specific functions." -> maybe use "provides" instead of "allows" and add a verb? ie. "**provides** certain groups of users **with** access to specific functions"

**Try what you’ll build**
- [x] combine the goals into one: `mvn clena install liberty:start-server`
- [x] is there anyway to logout and try another user? I logged in as bob, then went backwards (in browser) to try to login as another user but I got an authentication failure. Also stopping the servers and starting them up again results in `javax.servlet.ServletException: javax.el.ELException: Error reading 'userName' on type io.openliberty.guides.ui.SystemBean`. Is this all intentional?

**Adding the JWT Resource class**
- [x] can you create all directories and add .gitkeep into them so that the user don't have to do this themselves? It may be a bit tedious to create all of`backendServices/src/main/java/io/openliberty/guides/inventory` if you dont have `mkdir -p` at your disposal
- [x] you can simplify `getCustomClaim()` to just
```
if (securityContext.isUserInRole("admin")) {
  String customClaim = jwtPrincipal.getClaim("customClaim");
  return Response.ok(customClaim).build();
}
return Response.status(Response.Status.FORBIDDEN).build();
```
- [x] "The @GET annotation states that it is a HTTP GET request that will be used to access a method." -> this line is a bit confusing. The annotation simply indicates the type of http request the method handles. Since its a GET annotation, the method handles all http GET requests that come to its endpoint
- [x] "The getGroups(@Context SecurityContext securityContext) method" -> you dont need to include so much of the method signature like that, just saying `getGroups()` is enough (unless of course there are two methods with this name, which is not the case here).
- [x] "The getStatus(@Context SecurityContext securityContext) method" -> same as above point
- [x] `getStatus()` method is nowhere in the code, I think you meant to say `getCustomClaim()`?

**Add the InventoryResource class**
- [x] this class is used throughout multiple guides, why do we have to recreate it? You should provide this class and ask the users to tweak it to add the required annotations. Just say something like "Tweak InventoryResource.java and add the following annotation" or "Tweak InventoryResource.java and add the <list of annotations> for <purpose>". Then list the class as before and explain what each of the annotations do.
- [x] You dont need to reference the whole line of code: "The following code String authHeader...", using the variable name should be enough; ie. "The `authHeader` adds the authentication..."
- [x] "return Response.ok(manager.get(..." -> this bit of code is nowhere to be found. I think you meant to say `props`? If so, then same as the above point, just use the variable name to reference that line of code.

**Add the SystemClient class**
- [x] The `SystemClient` class is missing from the start directory. It should be provided. At this point, the app won't compile because SecuredSystemClient inherits from SystemClient
- [x] The title should also be "Add the SecuredSystemClient class"

**Add the SystemResource class**
- [x] This file should also be provided

**The User Object**
- [x] This file is missing, the start directory is empty

**Creating the login bean**
- [x] Remove "//context.addMessage(null, new FacesMessage("Login failed."));"
- [x] Reference `buildJWT()` and `getRole()` without all of the parameters

**Creating the Server Configuration File**
- [x] This is up to you, but I would rather provide this file, then just list it and explain the parts that matter. 

**Testing MP-JWT authorization**
- [x] Removed commented out lines from the `JwtTest` class.
- [x] Looks like there is a bunch of extra white space near the bottom of the `JwtTest` class as well.
- [x] After the test results listing block, write a sentence of two about a change a user can introduce themselves which will cause the tests to fail. The template at https://github.com/OpenLiberty/guides-common/blob/master/template.adoc has more info if you want.

**Great work! You’re done!**
- [x] Missing next steps: "Feel free to try one of the related MicroProfile guides. They demonstrate new technologies that you can learn and expand on top what you built here." is what I wrote in my guide at the end of the section.

**Comment by Kubik42** [comment]
#5 if it helps

**Comment by Kubik42** [comment]
#6 my attempt at creating the missing start directory

**Comment by jamiecoleman92** [comment]
I have made most of the required changes above in my last commit! I have some questions about some of the remaining changes that are required!

**Comment by evelinec** [comment]
@JunyiSun can you take a look at the unchecked boxes in this issue as well? Thank you.

**Comment by JunyiSun** [comment]
I have migrated the two unsolved issues to this specific issue: #12, this general issue can be closed

**Comment by Kubik42** [comment]
ok sounds good, thanks @JunyiSun
