### ISSUE TITLE
Feedback for 2/14's Draft

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-microprofile-jwt#7]
- Content
  - [x] Better to talk about the frontend first and then flow from there to the backend?  Otherwise, ensure that we provide adequate context and connect the dots clearly between the sections so users can easily understand our approach.
  - [x] Must have SME feedback and we need to describe what we have here in accurate technical terms throughout the guide -- The frontend and backend are secured; Tokens are used for authentication/authorization and to propagate identities; Frontend will authenticate users, create and then propagate tokens to the backend to retrieve resources from the backend; Backend services check for tokens, validate them, and then assert that users have necessary claims before responses are provided.
  - What you'll learn
    - [x] We should revise this section and explain what's necessary with proper terms (as noted above) ... For example, "You will add JWT authentication and authorization to the microservices provided" is weird.  We do not add JWT authentication and authorization but instrument the microservices to validates tokens and checks that users have rights to access?
   - [x] Rewrite the 2nd paragraph?  Was this taken from microprofile.io?
   - [x]  Section titles:  Better titles that reflect what users are accomplishing?  At least, fix "Testing MP-JWT authorization"?  Wasn't sure what it meant when I first saw it.
   - [x] "This feature allows you to use the MicroProfile JWT API to inject user authorization information in the RESTful services." -- This isn't accurate and we should revise it.  The feature does more than that.  It enables a service to use JWT and you can obtain the token via injection.  And, you only need to get the token if you need to validate custom claims.  Otherwise, you can use Java EE roles to assert what you need.
  - [x] Explain the purpose of the JwtResource better?  It really isn't part of the application but to show how you can retrieve the token and validate custom claims?  I won't make it the leading section either?
  - [x] Should we _not_ use mpJwt-1.0 instead?  This is a critical issue.

- Writing style (ID issues; @sishida )
  - [x] Document title, section titles:  Need to fix the style (e.g. capitalization) to match what we expect for the guides.
  - [x] Should "JWT Resource" for one of the titles be "JwtResource"?
  - [x] Use of MicroProfile, Microprofile, MP-JWT etc:  We need to be consistent and use the proper style.

- Code
  - [x] Should SecuredSystemClient be SecureSystemClient?
  - [x] Camel case for method names:  JWT should be Jwt, LogIn should be Login, UserName vs Username ... ?
  - [x] getInventorySize() for getInvSize()?
  - [x] Consistent formatting/style for messages/output and code comments?
  - [x] What do we return -1?  Can it be something better?

**Comment by GraceJansen** [comment]
Just some things I noticed during my peer review. But apart from this it looks great 👍 

- Are we using SystemResource.java or SystemResource for referring to creating the classes

- Extra line spaces in code for SystemResource.java

- buildJWT() creates a JWT token **which provides** user information -- have changed the grammar here

- getRole() returns the role **of** a user which is either admin or user -- change from for to of

- getUserName() returns the username of the user currently logged in **from the session** -- don't need this last bit, doesn't make sense

- Create a config file named server.xml in /start/frontendUI/src/main/liberty/config to pre-define users with their names, passwords and roles -- you are making folders here but haven't been for the rest of the instructions detailing making classes, do we need to state this or make it clear? (purely a question)

**Comment by yeekangc** [comment]
And, how do I logout if I want to try with a different user to see the difference?  This is a flaw with the current UI.

**Comment by sishida** [comment]
To me, "JWT Resource" looks like a name, but "JwtResource" looks like something that needs to be set off by a code phrase. If "JWT Resource" is the name, then I'd use that when referring to it in a title and limit "JwtResource" to refer to it when it appears in the actual code.

Unless it's part of code, use "MicroProfile" with a capital "M" and capital "P." It appears this way on the MicroProfile website and in our Knowledge Center. "MP-JWT" is capitalized and hyphenated unless it's also part of code.

**Comment by yeekangc** [comment]
In general, I feel we need to rework the guide to have a clear focus.

IMO, the focus is the how and why of services using mpJwt-1.0 to validate tokens and identify if there are valid users that can access the requested resources.  

The main scenario is the use of roles (via `@RolesAllowed`) and MP JWT to do roles-based access control.  The secondary case is the need to validate custom claims in the tokens.

Optionally and only if appropriate, we can cover the frontend aspects and token generation.  In real life, one would work with an Identify Provider or an Authentication service to accomplish these -- Not what we have in our sample so cannot be the focus.

**Comment by jamiecoleman92** [comment]
So has all the above not been implemented or has some of it already been done?

**Comment by evelinec** [comment]
@jamiecoleman92 You're the owner for the this issue/guide, apart from Junyi.

**Comment by evelinec** [comment]
@JunyiSun has the next action for this issue. Thanks.

**Comment by jamiecoleman92** [comment]
SME Feedback:

It is a great article!

I have reviewed the article, but I do not have chance to follow the lab yet (I will do it when I get time, and may provide more feedback).
1. Backend: We do not need configure jwtBuilder for back end, and we could just use microProfile-1.2 instead of listing all required features. (We decided against doing this right?)
(See attached file: server.xml)

2. Front end: The LoginBean.java should consider create a json array for groups.

**Comment by yeekangc** [comment]
I will reiterate my comment above that we need to rework the guide for a better focus.  @JunyiSun @evelinec, please take note.

**Comment by JunyiSun** [comment]
I have opened a new issue for the leftover one #18 . @yeekangc Please review the guide and see if we can close this issue.

**Comment by yeekangc** [comment]
In terms of what we have in this issue, yes.  Closing.
